Control_Machine_Sistem/Models/QrCode.cs
namespace Control_Machine_Sistem.Models
{
    public class QrCode
    {
        public string? ClientName { get; set; }
        public string? MachineModel { get; set; }
        public string? ManualUrl { get; set; }
        public string? DocUrl { get; set; }
        public DateTime? DeliveryDate { get; set; }       
        // Properties for printing
        public string? QrImageBase64 { get; set; }
        public string? QrContentUrl { get; set; }
    }
}

Control_Machine_Sistem/Controllers/MachinesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Control_Machine_Sistem.Models;
using Control_Machine_Sistem.ViewModels;
using System.Drawing.Printing;

namespace Control_Machine_Sistem.Controllers
{
    public class MachinesController : Controller
    {
        private readonly AppDbContext _context;

        public MachinesController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Machines
        public async Task<IActionResult> Index(string searchString, int page = 1, int pageSize = 5)
        {
            //var appDbContext = _context.Machines.Include(m => m.Customer).Include(m => m.Model);
            //return View(await appDbContext.ToListAsync());
            var machine = from m in _context.Machines!
                          .Include(m => m.Customer)
                          .Include(m => m.Model)
                          select m;

            //Filter by search text if provided
            if (!String.IsNullOrEmpty(searchString))
            {
                machine = machine.Where(s => s.Customer!.Name!.Contains(searchString) || s.Customer.LastName!.Contains(searchString) || 
                s.Model!.Name!.Contains(searchString));
            }

            // Get total machines 
            var totalMachines = await machine.CountAsync();

            // Apply pagination
            var machinePager = await machine
                           .Skip((page - 1) * pageSize)
                           .Take(pageSize)
                           .ToListAsync();

            // Create the paginator with the paginated list
            var pager = new Pager<Machine>(machinePager, totalMachines, page, pageSize);

            //To maintain the value of the lookup field when the user changes pages
            ViewData["searchString"] = searchString;
            return View(pager);
        }

        // GET: Machines/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var machine = await _context.Machines
                .Include(m => m.Customer)
                .Include(m => m.Model)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (machine == null)
            {
                return NotFound();
            }

            return View(machine);
        }

        // GET: Machines/Create
        public IActionResult Create()
        {         
            var customers = _context.Customers.Select(c => new
            {
                Id = c.Id,
                FullName = c.FullName
            }).ToList();
            ViewData["CustomerId"] = new SelectList(customers, "Id", "FullName");

            var models = _context.Models.Select(m => new
            {
                Id = m.Id,
                Name = m.Name
            }).ToList();
            ViewData["ModelId"] = new SelectList(models, "Id", "Name");

            return View();
        }

        // POST: Machines/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.    
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CustomerId,ModelId,ChasisNumber,EngineNumber,DeliveryDate,WarrantyExpirationDate,Documentations")] Machine machine)
        {
            if (ModelState.IsValid)
            {
                List<string> docUrls = new List<string>();

                if (machine.Documentations != null && machine.Documentations.Any())
                {
                    string uploadsFolder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "documentations", "machines");
                    Directory.CreateDirectory(uploadsFolder);

                    foreach (var documentation in machine.Documentations)
                    {
                        if (documentation.Length > 0)
                        {
                            string uniqueFileName = $"{Guid.NewGuid()}_{documentation.FileName}";
                            string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                            using (var fileStream = new FileStream(filePath, FileMode.Create))
                            {
                                await documentation.CopyToAsync(fileStream);
                            }

                            docUrls.Add($"/documentations/machines/{uniqueFileName}");
                        }
                    }
                }

                var newMachine = new Machine
                {
                    CustomerId = machine.CustomerId,
                    ModelId = machine.ModelId,
                    ChasisNumber = machine.ChasisNumber,
                    EngineNumber = machine.EngineNumber,
                    DeliveryDate = machine.DeliveryDate,
                    WarrantyExpirationDate = machine.WarrantyExpirationDate,
                    DocUrls = docUrls,
                };
                _context.Add(newMachine);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CustomerId"] = new SelectList(_context.Customers, "Id", "FullName", machine.CustomerId);
            ViewData["ModelId"] = new SelectList(_context.Models, "Id", "Name", machine.ModelId);
            return View(machine);
        }


        // GET: Machines/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var machine = await _context.Machines.FindAsync(id);

            if (machine == null)
            {
                return NotFound();
            }
            ViewData["CustomerId"] = new SelectList(_context.Customers, "Id", "FullName", machine.CustomerId);
            ViewData["ModelId"] = new SelectList(_context.Models, "Id", "Name", machine.ModelId);
            return View(machine);
        }

        // POST: Machines/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.     
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,CustomerId,ModelId,ChasisNumber,EngineNumber,DeliveryDate,WarrantyExpirationDate")] Machine machine, List<string> ExistingDocs, List<IFormFile> Documentations)
        {
            if (id != machine.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var existingMachine = await _context.Machines.FindAsync(id);

                    if (existingMachine == null)
                    {
                        return NotFound();
                    }
                    
                    existingMachine.CustomerId = machine.CustomerId;
                    existingMachine.ModelId = machine.ModelId;
                    existingMachine.ChasisNumber = machine.ChasisNumber;
                    existingMachine.EngineNumber = machine.EngineNumber;
                    existingMachine.DeliveryDate = machine.DeliveryDate;
                    existingMachine.WarrantyExpirationDate = machine.WarrantyExpirationDate;

                    List<string> docUrls = ExistingDocs ?? new List<string>();

                   
                    if (Documentations != null && Documentations.Any())
                    {
                        string uploadsFolder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "documentations", "machines");
                        Directory.CreateDirectory(uploadsFolder);

                        foreach (var documentation in Documentations)
                        {
                            if (documentation.Length > 0)
                            {
                                string uniqueFileName = $"{Guid.NewGuid()}_{documentation.FileName}";
                                string filePath = Path.Combine(uploadsFolder, uniqueFileName);

                                using (var fileStream = new FileStream(filePath, FileMode.Create))
                                {
                                    await documentation.CopyToAsync(fileStream);
                                }

                                docUrls.Add($"/documentations/machines/{uniqueFileName}");
                            }
                        }
                    }

                    existingMachine.DocUrls = docUrls;

                    _context.Update(existingMachine);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MachineExists(machine.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CustomerId"] = new SelectList(_context.Customers, "Id", "Id", machine.CustomerId);
            ViewData["ModelId"] = new SelectList(_context.Models, "Id", "Id", machine.ModelId);
            return View(machine);
        }


        // GET: Machines/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var machine = await _context.Machines
                .Include(m => m.Customer)
                .Include(m => m.Model)

Control_Machine_Sistem/Controllers/QrCodesController.cs
using Microsoft.AspNetCore.Mvc;
using Control_Machine_Sistem.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using QRCoder;
using Control_Machine_Sistem.ViewModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http.HttpResults;

namespace Control_Machine_Sistem.Controllers
{
    public class QrCodesController : Controller
    {
        private readonly AppDbContext _context;

        public QrCodesController(AppDbContext context)
        {
            _context = context;
        }

        // GET: QrCodes/GenerateQr/5
        [HttpGet]
        public async Task<IActionResult> GenerateQr(int machineId)
        {
            var machine = await _context.Machines
                .Include(m => m.Customer)
                .Include(m => m.Model)
                .FirstOrDefaultAsync(m => m.Id == machineId);

            if (machine == null || machine.Model == null || machine.Customer == null)
            {
                return NotFound();
            }

            var customer = machine.Customer;
            var manualUrls = machine.Model.ManualUrls ?? new List<string>();
            var manualUrl = manualUrls.Any()
                ? string.Join(", ", manualUrls)
                : "No hay manuales disponibles";

            var docUrls = machine.DocUrls ?? new List<string>();
            var docUrl = docUrls.Any()
                ? string.Join(", ", docUrls)
                : "No hay documentación disponible";

            var qrContentUrl = Url.Action("Details", "QrCodes", new { machineId }, Request.Scheme);

            var qrImageBase64 = GenerateQrCodeAsBase64(qrContentUrl!);

            var model = new QrCode
            {
                ClientName = customer.FullName,
                MachineModel = machine.Model.Name,
                ManualUrl = manualUrl,
                DocUrl = docUrl,
                QrContentUrl = qrContentUrl,
                QrImageBase64 = qrImageBase64
            };

            return View(model);
        }


        // Customer and machine selection page
        public async Task<IActionResult> Index()
        {
            var customers = await _context.Customers.Select(c => new SelectListItem
            {
                Value = c.Id.ToString(),
                Text = c.Name
            }).ToListAsync();

            var machines = await _context.Machines
                .Include(m => m.Customer)
                .Include(m => m.Model)
                .Select(m => new SelectListItem
                {
                    Value = m.Id.ToString(),
                    Text = $"{m.Customer!.Name} - {m.Model!.Name}"
                }).ToListAsync();

            var model = new QrCodeIndexViewModel
            {
                Clients = customers,
                Machines = machines
            };

            return View(model);
        }

        // QR generation
        [HttpPost]
        public async Task<IActionResult> postGenerateQr(int machineId)
        {
            var machine = await _context.Machines
                .Include(m => m.Customer)
                .Include(m => m.Model)
                .FirstOrDefaultAsync(m => m.Id == machineId);

            if (machine == null || machine.Model == null || machine.Customer == null)
            {
                return NotFound();
            }

            var customer = machine.Customer;
            var manualUrls = machine.Model.ManualUrls ?? new List<string>();
            var manualUrl = manualUrls.Any()
                ? string.Join(", ", manualUrls)
                : "No hay manuales disponibles";

            var docUrls = machine.DocUrls ?? new List<string>();
            var docUrl = docUrls.Any()
                ? string.Join(", ", docUrls)
                : "No hay documentación disponible";

            var qrContentUrl = Url.Action("Details", "QrCodes", new { machineId }, Request.Scheme);

            var qrImageBase64 = GenerateQrCodeAsBase64(qrContentUrl!);

            var model = new QrCode
            {
                ClientName = customer.FullName,
                MachineModel = machine.Model.Name,
                ManualUrl = manualUrl,
                DocUrl = docUrl,
                QrContentUrl = qrContentUrl,
                QrImageBase64 = qrImageBase64
            };

            return View(model);
        }

        private string GenerateQrCodeAsBase64(string content)
        {
            using var qrGenerator = new QRCodeGenerator();
            var qrCodeData = qrGenerator.CreateQrCode(content, QRCodeGenerator.ECCLevel.Q);
            using var qrCode = new PngByteQRCode(qrCodeData);
            var qrCodeImage = qrCode.GetGraphic(20);

            return $"data:image/png;base64,{Convert.ToBase64String(qrCodeImage)}";
        }

        // Action to view the details of the scanned QR
        public async Task<IActionResult> Details(int machineId)
        {
            var machine = await _context.Machines
                .Include(m => m.Customer)
                .Include(m => m.Model)
                .FirstOrDefaultAsync(m => m.Id == machineId);

            if (machine == null || machine.Model == null || machine.Customer == null)
            {
                return NotFound();
            }

            var manualUrls = machine.Model.ManualUrls;

            var manualUrl = manualUrls?.Any() == true
            ? string.Join(", ", manualUrls)
            : "No hay manuales disponibles";

            var docUrls = machine.DocUrls ?? new List<string>();

            var docUrl = docUrls?.Any() == true
                ? string.Join(", ", docUrls)
                : "No hay documentación disponible";

            var model = new QrCode
            {
                ClientName = machine.Customer.FullName,
                MachineModel = machine.Model.Name,
                ManualUrl = manualUrl,
                DocUrl = docUrl,
                DeliveryDate = machine.DeliveryDate,                
            };

            return View(model);
        }

        // Acción para mostrar los manuales
        public IActionResult ManualList(string urls)
        {
            var urlArray = urls.Split(',');

            if (!urlArray.Any())
            {
                return NotFound();
            }

            var manuals = urlArray.Select(url => new ManualViewModel
            {

                OriginalName = Path.GetFileName(url),

                DisplayName = Path.GetFileName(url).Split('_').Last()
            }).ToList();

            return View("ManualList", manuals);
        }

        public IActionResult DocumentList(string urls)
        {
            var urlArray = urls.Split(',');

            if (!urlArray.Any())
            {
                return NotFound();
            }

            var documents = urlArray.Select(url => new DocumentationViewModel
            {

                OriginalName = Path.GetFileName(url),

                DisplayName = Path.GetFileName(url).Split('_').Last()
            }).ToList();      
                      
            return View("DocumentList", documents);
        }

    }
}

Control_Machine_Sistem/Views/QrCodes/Details.cshtml
@* @model Control_Machine_Sistem.Models.QrCode

@{    
    ViewData["Title"] = "Detalles de la Máquina";
}

<h3>Sr @Model.ClientName</h3>
<h4>Modelo de Máquina: @Model.MachineModel</h4>
<h4>Fecha de Entrega:  @Model.DeliveryDate?.ToString("dd/MM/yyyy")</h4>

<ul>    
    <a href="@Url.Action("ManualList", "QrCodes", new { urls = Model.ManualUrl })" class="btn btn-primary">Descargar Manuales</a>
    <a href="@Url.Action("DocumentList", "QrCodes", new { urls = Model.DocUrl })" class="btn btn-primary">Descargar Documentación</a>
    <a href="#" class="btn btn-primary">Descargar Datos del Servicio Técnico</a>
</ul> *@

@model Control_Machine_Sistem.Models.QrCode

@{
    Layout = null;
    ViewData["Title"] = "Detalles de la Máquina";
}


<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

<div class="container mt-5">
    <div class="card">
        <div class="card-header">
            <h3>Sr @Model.ClientName</h3>
        </div>
        <div class="card-body">
            <h4>Modelo de Máquina: @Model.MachineModel</h4>
            <h4>Fecha de Entrega: @Model.DeliveryDate?.ToString("dd/MM/yyyy")</h4>
            <ul class="list-unstyled mt-3">
                <li>
                    <a href="@Url.Action("ManualList", "QrCodes", new { urls = Model.ManualUrl })" class="btn btn-primary mb-2">Descargar Manuales</a>
                </li>
                <li>
                    <a href="@Url.Action("DocumentList", "QrCodes", new { urls = Model.DocUrl })" class="btn btn-primary mb-2">Descargar Documentación</a>
                </li>
                <li>
                    <a href="#" class="btn btn-primary mb-2">Descargar Datos del Servicio Técnico</a>
                </li>
            </ul>
        </div>
    </div>
</div>

Control_Machine_Sistem/Views/QrCodes/DocumentList.cshtml
@using Control_Machine_Sistem.ViewModels
@model List<DocumentationViewModel>

    @{
        Layout = null;        
    }

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

<div class="container mt-5">
    <div class="card">
        <div class="card-header">
            <h2>Documentación de la Máquina</h2>
        </div>
        <div class="card-body">
            <ul class="list-group">
                @foreach (var doc in Model)
                {

                    var fileUrl = Url.Content("~/documentations/machines/" + doc.OriginalName);

                    <li class="list-group-item">
                        Descargar:
                        <a href="@fileUrl" target="_blank">
                           @doc.DisplayName
                        </a>
                    </li>
                }
            </ul>
            <br />
            <a href="javascript:history.back();" class="btn btn-secondary">
                Volver al menú principal
            </a>
        </div>
    </div>
</div>

Control_Machine_Sistem/Views/QrCodes/GenerateQr.cshtml
 @model Control_Machine_Sistem.Models.QrCode
@{
    ViewData["Title"] = "QR Generado";
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/qr.css" />   
</head>
<body>
    <div class="qr-container">
        <h1 class="center">Cliente: @Model.ClientName</h1>
        <h1 class="center">Modelo: @Model.MachineModel</h1>

        <div>
            <img src="@Model.QrImageBase64" alt="QR Code" class="qr-image" />
        </div>

        <div>
            <button onclick="window.print()" class="btn btn-success no-print">Imprimir QR</button>
        </div>

        <br/>

        <div>
            <a asp-controller="Machines" asp-action="Index" class="btn btn-secondary no-print">Volver a la lista</a>
        </div>

        <div class="print-only">
            <h2 class="center">Registro de Servicios</h2>
            <table class="service-table">
                <thead>
                    <tr>
                        <th>N° de Service</th>
                        <th>Fecha</th>
                        <th>Firma</th>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 1; i <= 8; i++)
                    {
                        <tr>
                            <td>@i</td>
                            <td></td>
                            <td></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</body>
</html>

Control_Machine_Sistem/Views/QrCodes/Index.cshtml
@model Control_Machine_Sistem.ViewModels.QrCodeIndexViewModel

@{
    ViewData["Title"] = "Generar QR";
}

<h1>Generar codigo QR</h1>
<hr/>
<form method="post" asp-action="GenerateQr">
    <div class="form-group">
        <label for="machine">Seleccione una Máquina:</label>
        <select class="form-control" id="machine" name="machineId">
            <option value="">Máquina</option>
            @foreach (var machine in Model.Machines!)
            {
                <option value="@machine.Value">
                    @machine.Text
                </option>
            }
        </select>
    </div>
    <br />
    <button type="submit" class="btn btn-success">Generar QR</button>
</form>

Control_Machine_Sistem/Views/QrCodes/ManualList.cshtml
@using Control_Machine_Sistem.ViewModels
@model List<ManualViewModel>

@{
    Layout = null;    
}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

<div class="container mt-5">
    <div class="card">
        <div class="card-header">
            <h2>Manuales de la Máquina</h2>
        </div>
        <div class="card-body">
            <ul class="list-group">
                @foreach (var manual in Model)
                {

                    var fileUrl = Url.Content("~/manuals/models/" + manual.OriginalName);

                    <li class="list-group-item">
                        Descargar:
                        <a href="@fileUrl" target="_blank">
                           @manual.DisplayName
                        </a>
                    </li>
                }
            </ul>
            <br />
            <a href="javascript:history.back();" class="btn btn-secondary">
                Volver al menú principal
            </a>
        </div>
    </div>
</div>